### PR TITLE
Use Github Actions as CI

### PR DESCRIPTION
**Pull request by martin-g**
Fix the environment variables declaration

### CODE REVIEW

**Review by solomax — APPROVED** [review]
+1 :)))
Any options to put email notification?

**Comment by solomax** [comment]
```
Misconfigured toolchains. Non-existing JDK home configuration at /home/travis/oraclejdk11 -> [Help 1]
```

**Comment by martin-g** [comment]
> Any options to put email notification?

I've found this - https://www.ravsam.in/blog/send-email-notification-when-github-action-fails/

**Comment by martin-g** [comment]
Or set it up to send you notifications for **your** failed workflows at https://github.com/settings/notifications

**Comment by martin-g** [comment]
later I will see how to re-add the logic to deploy to oss.sonatype.org when the event is a push to master

**Pull request merged**
