### PR TITLE
Upgrading to Wicket 10, Spring 6 and related Jakarta EE specs

### PR DESCRIPTION
**Pull request by ilgrosso**
Following #740 
Before merging this request to `master` branch, the `master` branch shall be copied as the new `wicket-9.x` branch.

Still draft because:

1. ~~`mvn clean install -DskipTests` works fine, but test results were not checked yet~~
2. replacement for Wicket class removals (in particular `ModalWindow`) are to be checked

### CODE REVIEW

**Comment by martin-g** [comment]
I will create branch `wicket-9.x` from master and leave `master` for 10.x

**Comment by martin-g** [comment]
Done: https://github.com/wicketstuff/core/tree/wicket-9.x

**Comment by ilgrosso** [comment]
@martin-g the branch should be changed in https://github.com/wicketstuff/core/blob/wicket-9.x/.github/workflows/ci.yml

**Comment by martin-g** [comment]
> @martin-g the branch should be changed in https://github.com/wicketstuff/core/blob/wicket-9.x/.github/workflows/ci.yml

Fixed it! Thanks!

**Comment by ilgrosso** [comment]
All tests are passing locally but GitHub Actions goes error 

```
Error:  org.wicketstuff.pageserializer.kryo2.KryoSerializerTest.homepageRendersSuccessfully  Time elapsed: 0.114 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: The produced data length is not correct! ==> expected: <777> but was: <776>
```

See https://github.com/wicketstuff/core/actions/runs/3847139651/jobs/6553240311#step:5:10121

**Comment by martin-g** [comment]
This is a known issue.
I'd just remove this assertion. It is too unstable.

**Comment by ilgrosso** [comment]
@martin-g now that build is green, I'd ask you to review this PR, especially for the changes due to Wicket upgrade.

In particular `ModalWindow` -> `ModalDialog` since it seems that the latter has way less methods than the former, and I've simply removed the calls to missing methods: please advice if there is a better way, thanks.

**Review by martin-g — APPROVED** [review]
LGTM!

About the ModalWindow->ModalDialog changes - we can always fix them later if there are issues!

**Comment by ilgrosso** [comment]
Thank you @martin-g !

**Comment by martin-g** [comment]
I'm uploading -SNAPSHOT from my machine...

**Comment by ilgrosso** [comment]
Ah, thank you

**Comment by martin-g** [comment]
Forgot to mention that the upload/deploy is done!

**Comment by solomax** [comment]
great job @ilgrosso!
Thanks a lot :)))

**Comment by ilgrosso** [comment]
@solomax my pleasure

**Comment by jeronimo75** [comment]
Just for you to know, your port is missing a line of code to be completely ok.
Because now ModalContentWindows extends ModalDialog, you need to add:
		add(new DefaultTheme());
to the constructor of ModalContentWindows for it to work as before.
Else the style is not applied and nothing is rendering correctly and nothing is clickable.

**Comment by ilgrosso** [comment]
Nice spot @jeronimo75 
Why don't you submit a PR with the fix, then?

**Comment by solomax** [comment]
> Just for you to know, your port is missing a line of code to be completely ok. Because now ModalContentWindows extends ModalDialog, you need to add: add(new DefaultTheme()); to the constructor of ModalContentWindows for it to work as before. Else the style is not applied and nothing is rendering correctly and nothing is clickable.

Done in 720a3c8130

**Pull request merged**
