### PR TITLE
Fix IChoiceRenderer support. Added examples with stateless Select2Choice...

### PR DESCRIPTION
**Pull request by shuraa**
... component.

- refine choice conversion for multiple variants
- use IChoiceRenderer to render current value both for Select2Choice and Select2MultiChoice
- added more constructors (both with IChoiceRenderer)

### CODE REVIEW

**Comment by shuraa** [comment]
@solomax , @martin-g , please, review another PR.

PS
Should I after PR merge create another PR with merge for master?

**Comment by solomax** [comment]
I see no issues with this PR @martin-g do you have any comments?

**Comment by martin-g** [comment]
Merged!

@shuraa Please provide PRs for master branch too. Thanks!

**Comment by shuraa** [comment]
PR to master https://github.com/wicketstuff/core/pull/398

**Pull request merged**
