### PR TITLE
Reformat select2 code

### PR DESCRIPTION
**Pull request by shuraa**
... according to http://mvnrepository.com/artifact/org.apache.wicket/wicket-eclipse-settings

### CODE REVIEW

**Comment by reiern70** [comment]
Wouldn't this make tracking issues a lot more difficult?

**Comment by solomax** [comment]
I personally will better have well formatted code, not sure if I need to start discussion on that ....
should I?

**Comment by reiern70** [comment]
let's see what @martin-g  and other commiters thinks ;-) 

I still have some "private" version of select2 with things that might be good additions. I will wait for this to be applied or rejected to create a PR adding those.

**Comment by martin-g** [comment]
Formatting only changes are actually what I prefer.
I do not like PRs with fix/improvement that also have formatting noise.

**Comment by solomax** [comment]
Great!
Thanks a lot Martin :)

**Pull request merged**
