### PR TITLE
liferay 6.2 wicket portlet examples

### PR DESCRIPTION
**Pull request by kkaravitis**
Hello,

I created the wicket-portlet-examples module under portlet-parent in order to help everyone who wants to test the wicket 7 examples as portlets in liferay 6.2.

Please take a look and tell me if you agree with it.

Thank you!

### CODE REVIEW

**Comment by martin-g** [comment]
The changelist is huge so I checked only the first N files.
The rest is copied from wicket-examples anyway, so I trust it is top quality! :-)

Thanks a lot for reviving this project, @kkaravitis!

**Comment by kkaravitis** [comment]
Thank you too!
I hope this project will help the wicket users who develop portlets!
Στις 8 Απρ 2016 6:15 μ.μ., ο χρήστης "Martin Grigorov" <
notifications@github.com> έγραψε:

**Comment by martin-g** [comment]
Maybe it is a good idea to add a README.md in the examples project with description how to deploy it at Liferay/AnotherPortletContainer ?
For people like me who have zero experience with portlets ?

**Comment by martin-g** [comment]
...or an entry at https://github.com/wicketstuff/core/wiki.

**Comment by kkaravitis** [comment]
It is a very good idea :)

I will write a tutorial for working with the portlet examples by using the
eclipse and liferay ide.

**Pull request merged**
