### PR TITLE
Issue #850: Merging wicket jquery UI into wicketstuff core (9.x)

### PR DESCRIPTION
**Pull request by reckart**
- [x] Moved Wicket JQuery / Kendo into subfolders
- [x] Integrated Wicket JQuery / Kendo modules into the build process
- [x] Remove redundancies from the wicket-jquery-ui-parent pom - everything necessary should be in the wicketstuff parent POM already
- ~Change groupIds to match wicketstuff~ (not for 9.x)
- ~Change artifactIds to match  wicketstuff conventions~ (not for 9.x)
- ~Change module names to match wicketstuff conventions~ (not for 9.x)
- ~Change package names to match wicketstuff~ (not for 9.x)

### CODE REVIEW

**Review by solomax — APPROVED** [review]

**Comment by solomax** [comment]
@reckart I would modify description and remove 
`Change groupIds to match wicketstuff`
and
`Change artifactIds to match wicketstuff conventions`

otherwise we will lose backward compatibility :)

**Comment by reckart** [comment]
Mind if we keep the old groupIds, we have a release that contains multiple groupIds. Do you know if that has implications when deploying to Maven Central / Nexus?

**Comment by solomax** [comment]
Originally it was deployed to https://oss.sonatype.org (same as wicketstuff)

After merge I can run release process, and we will check if there will be any issues :)

**Comment by reckart** [comment]
Ok, I have change the groupIds of the Wicket JQuery UI / Kendo modules back to the old one for backwards compatibility. Anything more to do before merging?

**Comment by solomax** [comment]
Merged, I'll try to check everything locally ASAP!

**Comment by solomax** [comment]
@reckart SNAPSHOT succesfully deployed to https://oss.sonatype.org/

**Comment by solomax** [comment]
Can someone suggest how to get filtered `shortlog`?

with this 1000+ commits PR usual shortlog is useless :((((

**Comment by reckart** [comment]
I don't find a way at the moment of excluding a certain commit or range of commits from the shortlog. My idea would be to check the authors of the original wicket-jquery repo and then manually remove most/all the authors from that from the shortlog for the current releases, assuming that there is no significant relevant overlap between the authors of the two repos or the contributions they have made to the two repos in the relevant time spans.

**Comment by reckart** [comment]
Maybe: `git shortlog wicketstuff-core-9.17.0..wicketstuff-core-9.18.0 --not 6d27a309d9d94bf1355ce5abeaacff3ce9e9dfbd` - the hash is the commit where we merged wicket-jquery

**Comment by solomax** [comment]
Thanks a million @reckart !

**Pull request merged**
