### PR TITLE
Fix similar mapped path (very similar problem of #462)

### PR DESCRIPTION
**Pull request by niwatolli3**
I have the following **three** methods mapped:

```java
	@MethodMapping(value = "/user/auth/", httpMethod = HttpMethod.POST)
	public Object AuthUserByEmail(@RequestBody User user) {
		return "hoge";
	}
	
	@MethodMapping(value = "/user/login/", httpMethod = HttpMethod.POST)
	public Object login(@RequestBody User user) {
		return "hoge";
	}
	
	@MethodMapping(value = "/user/logout/", httpMethod = HttpMethod.POST)
	public Object logout(@RequestBody User user) {
		return "hoge";
	}
```

When I visit this url localhost:8080/mountpoint/path/user/auth, I get the following error:
```java
WARN  - RequestCycleExtra          - ********************************
WARN  - RequestCycleExtra          - Handling the following exception
org.apache.wicket.WicketRuntimeException: Ambiguous methods mapped for the current request: URL 'api/v1/user/auth', HTTP method POST. Mapped methods: logout, login
	at org.wicketstuff.rest.resource.AbstractRestResource.throwAmbiguousMethodsException(AbstractRestResource.java:494)
	at org.wicketstuff.rest.resource.AbstractRestResource.selectMostSuitedMethod(AbstractRestResource.java:460)
	at org.wicketstuff.rest.resource.AbstractRestResource.respond(AbstractRestResource.java:180)
	at org.apache.wicket.request.handler.resource.ResourceRequestHandler.respond(ResourceRequestHandler.java:105)
	at org.apache.wicket.request.handler.resource.ResourceReferenceRequestHandler.respond(ResourceReferenceRequestHandler.java:108)
	at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:895)
	at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:64)
	at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:265)
	at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:222)
	at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:293)
	at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:261)
	at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:203)
	at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:284)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
WARN  - RequestCycleExtra          - ********************************
ERROR - DefaultExceptionMapper     - Unexpected error occurred
org.apache.wicket.WicketRuntimeException: Ambiguous methods mapped for the current request: URL 'api/v1/user/auth', HTTP method POST. Mapped methods: logout, login
	at org.wicketstuff.rest.resource.AbstractRestResource.throwAmbiguousMethodsException(AbstractRestResource.java:494)
	at org.wicketstuff.rest.resource.AbstractRestResource.selectMostSuitedMethod(AbstractRestResource.java:460)
	at org.wicketstuff.rest.resource.AbstractRestResource.respond(AbstractRestResource.java:180)
	at org.apache.wicket.request.handler.resource.ResourceRequestHandler.respond(ResourceRequestHandler.java:105)
	at org.apache.wicket.request.handler.resource.ResourceReferenceRequestHandler.respond(ResourceReferenceRequestHandler.java:108)
	at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:895)
	at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:64)
	at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:265)
	at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:222)
	at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:293)
	at org.apache.wicket.protocol.http.WicketFilter.processRequestCycle(WicketFilter.java:261)
	at org.apache.wicket.protocol.http.WicketFilter.processRequest(WicketFilter.java:203)
	at org.apache.wicket.protocol.http.WicketFilter.doFilter(WicketFilter.java:284)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
```

I fixed the problem. 
You can run the test by running testSimilarMountedPath() which is already exists in RestResourcesTest.java

Please check my PR and give me feedback.

### CODE REVIEW

**Comment by martin-g** [comment]
@bitstorm  Please review and merge this PR when you have time. I'm going to release 6.23/7.3 in the coming days.

**Comment by bitstorm** [comment]
Merged with #462

**Comment by niwatolli3** [comment]
Hi, @bitstorm 
This is not solved in #462 so that I wrote the commit.

Two similar methods is ok but more than two is NG.

Could you check this commit and #462?

**Comment by bitstorm** [comment]
Hi @niwatolli3 

WicketStuff 7.3.0 has not been released yet, but with 7.3.0-SNAPSHOT thi bug should be fixed. I've successfully tested the code  you see in this gist:

https://gist.github.com/bitstorm/e140231286a8b55d1546d342f2bf7d5c

**Comment by martin-g** [comment]
I have released 7.3.0/6.23.0 few hours ago.
I haven't announced them yet. I was waiting for them to appear at Maven Central.
Probably they are already there. I'll announce them soon!

**Comment by bitstorm** [comment]
Thank you Martin!

**Comment by niwatolli3** [comment]
Dear @bitstorm , @martin-g 

Thank you for your comment.
This commit will be merged in next version, right?

**Comment by bitstorm** [comment]
@niwatolli3  sorry but I don't see the point of your question. Wicketstuff 7.3.0 contains the commit b1e25509c58eb84744a3b376d2ce3c9364a2f335 which also solves this issue. Why do you still need the commit of this pull request?

**Comment by niwatolli3** [comment]
@bitstorm,

I am sorry for the lack of explanation. 
This exception will be occurred occasionally.

Please run your test code(https://gist.github.com/bitstorm/e140231286a8b55d1546d342f2bf7d5c) more than 10 times.
You will see that this test code will be failed occasionally.

I show the stack trace below:
<pre>
INFO  - Application                - [WicketTesterApplication-66af2da8-afb7-4ebf-99e3-4eb95a4acce9] init: Wicket core library initializer
INFO  - RequestListenerInterface   - registered listener interface [RequestListenerInterface name=IBehaviorListener, method=public abstract void org.apache.wicket.behavior.IBehaviorListener.onRequest()]
INFO  - RequestListenerInterface   - registered listener interface [RequestListenerInterface name=IFormSubmitListener, method=public abstract void org.apache.wicket.markup.html.form.IFormSubmitListener.onFormSubmitted()]
INFO  - RequestListenerInterface   - registered listener interface [RequestListenerInterface name=ILinkListener, method=public abstract void org.apache.wicket.markup.html.link.ILinkListener.onLinkClicked()]
INFO  - RequestListenerInterface   - registered listener interface [RequestListenerInterface name=IOnChangeListener, method=public abstract void org.apache.wicket.markup.html.form.IOnChangeListener.onSelectionChanged()]
INFO  - RequestListenerInterface   - registered listener interface [RequestListenerInterface name=IResourceListener, method=public abstract void org.apache.wicket.IResourceListener.onResourceRequested()]
WARN  - RequestCycleExtra          - ********************************
WARN  - RequestCycleExtra          - Handling the following exception
org.apache.wicket.WicketRuntimeException: Ambiguous methods mapped for the current request: URL 'api/user/login?term=ff', HTTP method POST. Mapped methods: AuthUserByEmail, logout
	at org.wicketstuff.rest.resource.AbstractRestResource.throwAmbiguousMethodsException(AbstractRestResource.java:490)
	at org.wicketstuff.rest.resource.AbstractRestResource.selectMostSuitedMethod(AbstractRestResource.java:456)
	at org.wicketstuff.rest.resource.AbstractRestResource.respond(AbstractRestResource.java:179)
	at org.apache.wicket.request.handler.resource.ResourceRequestHandler.respond(ResourceRequestHandler.java:105)
	at org.apache.wicket.request.handler.resource.ResourceReferenceRequestHandler.respond(ResourceReferenceRequestHandler.java:108)
	at org.apache.wicket.request.cycle.RequestCycle$HandlerExecutor.respond(RequestCycle.java:895)
	at org.apache.wicket.request.RequestHandlerStack.execute(RequestHandlerStack.java:64)
	at org.apache.wicket.request.cycle.RequestCycle.execute(RequestCycle.java:265)
	at org.apache.wicket.request.cycle.RequestCycle.processRequest(RequestCycle.java:222)
	at org.apache.wicket.request.cycle.RequestCycle.processRequestAndDetach(RequestCycle.java:293)
	at org.apache.wicket.util.tester.BaseWicketTester.processRequest(BaseWicketTester.java:714)
	at org.apache.wicket.util.tester.BaseWicketTester.processRequest(BaseWicketTester.java:653)
	at org.apache.wicket.util.tester.BaseWicketTester.processRequest(BaseWicketTester.java:625)
	at org.apache.wicket.util.tester.BaseWicketTester.executeUrl(BaseWicketTester.java:2741)
	at org.wicketstuff.rest.RestResourcesTest.test(RestResourcesTest.java:139)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
WARN  - RequestCycleExtra          - ********************************
INFO  - Application                - [WicketTesterApplication-66af2da8-afb7-4ebf-99e3-4eb95a4acce9] destroy: Wicket core library initializer
</pre>

This bug depends on order of mappedMethodsCandidates's content.

I will show you the score for each method mapping
/user/login -> 4 point
/user/auth -> 2 point
/user/logout -> 2 point

If the order of mappedMethodsCandidates's is like below, this test will be failed.
/user/auth -> 2 point
/user/logout -> 2 point
/user/login -> 4 point

because,
<pre>
			if(highestScore > 0 && scoredMethod.getScore() == highestScore)
</pre>
This if statement will be true.

On the other hand,
/user/auth -> 2 point
/user/login -> 4 point
/user/logout -> 2 point

or,
/user/login -> 4 point
/user/auth -> 2 point
/user/logout -> 2 point

This test code will be succeeded.

So, we should treat this problem.

Please excuse my poor English.
Could you see my PR?

**Comment by bitstorm** [comment]
Hi @niwatolli3 ,

thank you for your explanation, now I see the problem. I should commit a fix based on your PR in the very next days.

**Comment by niwatolli3** [comment]
Hi @bitstorm,

Thank you for your response!

**Comment by chrisco484** [comment]
Unrelated to the bug but I just discovered that REST capabilities were in a wicketstuff library and prompts me to ask: Wicket is a HTML based UI framework so what part does REST play? There are probably hundreds of REST client/service Java libs out there. Why is this one in Wicketstuff - is there any kind of special integration with Wicket the core that might be useful or is it just a stand alone REST library within wicketstuff? I'm not trying to be rude but trying to understand its purpose as maybe I'm missing some key feature of this Wicketstuff REST capability.

**Comment by bitstorm** [comment]
Hi @chrisco484,

Wicket is indeed a HTML based UI framework, but it also comes with a more general abstraction of web resource.  So it came quite naturally creating an extension for REST resources (hence this is not a stand-alone library). In addition this library can be easily integrated with custom Wicket entities like:

-Validators
-IRoleCheckingStrategy for authorizations
-Data converters (IConverter)

Of course you are free to use your favourite REST library with Wicket if you are not interested in such features.

**Comment by bitstorm** [comment]
Hi @niwatolli3 ,

I've commited a slightly different fix (5c987ad) for this issue which uses utility class MultiMap. This class comes quite in handy for our problem as it allows to count how many candidate methods we have for the highest score with nearly no effort.

**Comment by niwatolli3** [comment]
Hi, @bitstorm 

Thank you for your fix commit :-D
I think that this commit is good.

Thanks!

**Pull request closed without merging**
