### PR TITLE
fix for issue #540 "WicketPortlet attempts to modify immutable map" 

### PR DESCRIPTION
**Pull request by kkaravitis**
Code refactoring after review advice on 2f930ff commit

### CODE REVIEW

**Comment by martin-g** [comment]
@kkaravitis Are those changes merged to master too (8.x) ?
I've just tried to cherry-pick this one but it seems the previous are not there yet.

**Comment by kkaravitis** [comment]
@martin-g 
Unfortunately I have not found time to setup a java 8 portal environment and test the bridge, so the changes have not been merged to the master. For now, I am working on wicket-7.x branch because I use wicket 7 on my projects and it is easy for me to test against liferay and websphere.

**Comment by martin-g** [comment]
I don't test all my changes in all branches as well.
But if the fixes are not merged to the NEXT branch then there is a big chance that the same problems will be faced and reported later.

**Comment by kkaravitis** [comment]
Ok, I will merge the necessary changes as soon as possible to the master.

**Pull request merged**
