### PR TITLE
[serializer-fast] [serializer-fast2] upgrade fast to 1.63 and 2.10

### PR DESCRIPTION
**Pull request by gsmet**
Fixes a bug regarding we spotted while testing our apps regarding the Externalizable support.

### CODE REVIEW

**Comment by martin-g** [comment]
It seems both Fast and Fast2 integrations are broken in `wicket-6.x`.
@gsmet Do you have time to fix them today? Or I should release 6.19.0 without them ?

**Comment by gsmet** [comment]
@martin-g any pointers on where it is failing? I should be able to take a look at it today.

**Comment by martin-g** [comment]
`mvn test` and it will tell you all the details ;-)

**Comment by bitstorm** [comment]
Failed tests:   homepageRendersSuccessfully(org.wicketstuff.pageserializer.kryo2.KryoSerializerTest): The produced data length is not correct! expected:<400> but was:<402>

**Comment by gsmet** [comment]
https://github.com/wicketstuff/core/pull/382

>

**Pull request merged**
