### PR TITLE
#933 Use Webjars for JQuery UI themes

### LINKED ISSUE #933: Error during startup when using a non-default theme

### PR DESCRIPTION
**Pull request by mcr-paulanand**
Resolves #933

### CODE REVIEW

**Comment by solomax** [comment]
I believe this PR should be closed and shouldn't be merged

you are replacing customized **themed** CSS with the default one ...

this will effectively ruin theming :(

**Comment by reckart** [comment]
The Webjars install in this PR seems to be essential for me, otherwise my app won't start (i.e. with the 10.1.0 release, it won't start).

**Comment by solomax** [comment]
@reckart I believe you need to add 'install' to your app's 'init'

I'll try to check this branch locally and will report back

**Comment by reckart** [comment]
The init method runs after the SPI-injected initializers and the theme initializer already triggers a webjar access.

**Comment by solomax** [comment]
> The init method runs after the SPI-injected initializers and the theme initializer already triggers a webjar access.

I did some testing:
 - clone repo for this PR
 - build 51 subproject of `wicket-jquery-ui`
 - `cd wicketstuff-jquery-ui-samples`
 - change the theme to be `wicketstuff-jquery-ui-theme-eggplant`
 - run samples
Result: theme remain the same

 - Tested the release with the same steps
Result: Samples were not started

My conclusion: `WicketWebjars.install((WebApplication)application);` MUST be added to all Initializers

This PR: shouldn't be merged as-is ...

New release seems to be required :(

**Comment by solomax** [comment]
I can create alternative pr for review later today :)

**Comment by solomax** [comment]
> I can create alternative pr for review later today :)

Done: https://github.com/wicketstuff/core/pull/935 :)))

**Pull request closed without merging**
