### PR TITLE
tinymce6: fix webjars version

### PR DESCRIPTION
**Pull request by vrozkovec**
pom.xml includes version 6.8.3

### CODE REVIEW

**Comment by solomax** [comment]
@vrozkovec maybe it would be possible to use `latest`?

**Comment by vrozkovec** [comment]
It would be the best but I didn't get to it yet, will check later if/how that is possible.

**Comment by martin-g** [comment]
You just need to replace the version (x.y.z) with ‘latest’. wicket-webjars
has logic to resolve the version from the resources in the classpath

**Comment by vrozkovec** [comment]
Shouldn't it be `current` instead? Looking here: https://github.com/martin-g/wicket-webjars/blob/31b02fcf6e4f5e6bd7a3cf8895e75dfa1a6dd787/library/src/main/java/de/agilecoders/wicket/webjars/settings/WebjarsSettings.java#L49

But maybe I'm mixing things up, this is related to wicket-bootstrap but I couldn't find any other reference to webjars in Wicket 10.x guide. Like I said, didn't really have time to dig in deeper.

**Comment by solomax** [comment]
> Shouldn't it be `current` instead? Looking here: https://github.com/martin-g/wicket-webjars/blob/31b02fcf6e4f5e6bd7a3cf8895e75dfa1a6dd787/library/src/main/java/de/agilecoders/wicket/webjars/settings/WebjarsSettings.java#L49
> 

Yes, `current` is correct: https://github.com/martin-g/wicket-bootstrap/blob/wicket-10.x-bootstrap-5.x/bootstrap-extensions/src/main/java/de/agilecoders/wicket/extensions/markup/html/bootstrap/form/tempusdominus/TempusDominusBehavior.java#L52 :)

**Comment by vrozkovec** [comment]
Updated

**Comment by solomax** [comment]
I would say there is no need to have separate JSRef from minified library ... :)

**Comment by solomax** [comment]
@vrozkovec Thanks for the contribution!

**Pull request merged**
