### PR TITLE
#933 - Error during startup when using a non-default theme

### PR DESCRIPTION
**Pull request by solomax**
* Register Webjars in the initializer of every theme
* Added script to update themes
* Updated all themes

### CODE REVIEW

**Comment by solomax** [comment]
@reckart @mcr-paulanand please take a look :)

all themes are updated as well, basic script to get fresh themes is added :)

**Review by reckart — APPROVED** [review]

**Comment by solomax** [comment]
Please let me know when shall start new release :)

**Comment by reckart** [comment]
@solomax as the saying goes: after the release is before the release - atm I see no reason not to release but I can't promise there won't be another obstacle we might hit in another couple of days when there is more testing...

**Comment by solomax** [comment]
@reckart I'll do the release tomorrow :)))

**Pull request merged**
